#!/bin/sh
# ON FORCE LA CONFIGURATION PIZERO USBC
cmake -G "Unix Makefiles" \
  -DFAMILY=rp2040 \
  -DPICO_BOARD=waveshare_rp2040_zero \
  -DPICO_USB_HOST_DP_PIN=6 \
  -DPICO_USB_HOST_DM_PIN=7 \
  -DCONFIG_USB=1 \
  -DPICO_PIO_USB_CLOCK_KHZ=120000 \
  -B build
